package dev.bikram.remember.ui.edit

import dev.bikram.remember.R

/**
 * Curated note icons: Material Symbols (Rounded) + brand PNGs where Symbols omit trademarks.
 * Non-brand keys use [ICON_SYMBOL_PREFIX]; brand keys use [ICON_DRAWABLE_PREFIX].
 * Categories are grouped for the picker (not every ligature fits one label).
 */
internal val bundledMaterialSymbolIconCategories: List<IconCategory> = listOf(
    IconCategory(
        nameRes = R.string.icon_section_notes_ideas,
        icons = listOf(
            IconChoice(key = "${ICON_SYMBOL_PREFIX}note_add", symbolName = "note_add", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}list", symbolName = "list", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}lightbulb", symbolName = "lightbulb", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}note", symbolName = "note", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}bookmark", symbolName = "bookmark", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}book", symbolName = "book", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}menu_book", symbolName = "menu_book", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}inventory_2", symbolName = "inventory_2", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}bug_report", symbolName = "bug_report", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}favorite", symbolName = "favorite", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}thumb_up", symbolName = "thumb_up", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}thumb_down", symbolName = "thumb_down", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}feed", symbolName = "feed", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}campaign", symbolName = "campaign", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}newspaper", symbolName = "newspaper", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}calculate", symbolName = "calculate", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}anchor", symbolName = "anchor", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}chair", symbolName = "chair", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}label", symbolName = "label", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}dataset", symbolName = "dataset", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}rocket", symbolName = "rocket", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}light", symbolName = "light", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}candlestick_chart", symbolName = "candlestick_chart", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}recycling", symbolName = "recycling", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}workspace_premium", symbolName = "workspace_premium", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}diamond", symbolName = "diamond", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}balance", symbolName = "balance", drawableRes = null),
        ),
    ),
    IconCategory(
        nameRes = R.string.icon_section_money,
        icons = listOf(
            IconChoice(key = "${ICON_SYMBOL_PREFIX}attach_money", symbolName = "attach_money", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}euro", symbolName = "euro", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}currency_pound", symbolName = "currency_pound", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}currency_rupee", symbolName = "currency_rupee", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}currency_ruble", symbolName = "currency_ruble", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}currency_exchange", symbolName = "currency_exchange", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}currency_lira", symbolName = "currency_lira", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}currency_yen", symbolName = "currency_yen", drawableRes = null),
        ),
    ),
    IconCategory(
        nameRes = R.string.icon_section_messages_calls,
        icons = listOf(
            IconChoice(key = "${ICON_SYMBOL_PREFIX}call", symbolName = "call", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}phone_callback", symbolName = "phone_callback", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}phone_forwarded", symbolName = "phone_forwarded", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}call_end", symbolName = "call_end", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}phone_missed", symbolName = "phone_missed", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}ring_volume", symbolName = "ring_volume", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}voicemail", symbolName = "voicemail", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}no_sim", symbolName = "no_sim", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}mic", symbolName = "mic", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}mic_off", symbolName = "mic_off", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}mail", symbolName = "mail", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}send", symbolName = "send", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}sms", symbolName = "sms", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}comments_disabled", symbolName = "comments_disabled", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}comment", symbolName = "comment", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}chat", symbolName = "chat", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}chat_bubble", symbolName = "chat_bubble", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}chat_bubble_outline", symbolName = "chat_bubble_outline", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}import_contacts", symbolName = "import_contacts", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}contacts", symbolName = "contacts", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}import_export", symbolName = "import_export", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}call_merge", symbolName = "call_merge", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}call_missed", symbolName = "call_missed", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}call_missed_outgoing", symbolName = "call_missed_outgoing", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}call_split", symbolName = "call_split", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}swap_calls", symbolName = "swap_calls", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}translate", symbolName = "translate", drawableRes = null),
        ),
    ),
    IconCategory(
        nameRes = R.string.icon_section_schedule,
        icons = listOf(
            IconChoice(key = "${ICON_SYMBOL_PREFIX}calendar_today", symbolName = "calendar_today", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}calendar_month", symbolName = "calendar_month", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}lock_clock", symbolName = "lock_clock", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}alarm", symbolName = "alarm", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}add_alarm", symbolName = "add_alarm", drawableRes = null),
        ),
    ),
    IconCategory(
        nameRes = R.string.icon_section_security_privacy,
        icons = listOf(
            IconChoice(key = "${ICON_SYMBOL_PREFIX}lock", symbolName = "lock", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}lock_open", symbolName = "lock_open", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}key", symbolName = "key", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}visibility_off", symbolName = "visibility_off", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}visibility", symbolName = "visibility", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}shield", symbolName = "shield", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}fingerprint", symbolName = "fingerprint", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}verified_user", symbolName = "verified_user", drawableRes = null),
        ),
    ),
    IconCategory(
        nameRes = R.string.icon_section_shopping_care,
        icons = listOf(
            IconChoice(key = "${ICON_SYMBOL_PREFIX}flashlight_on", symbolName = "flashlight_on", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}shopping_basket", symbolName = "shopping_basket", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}shopping_cart", symbolName = "shopping_cart", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}dry_cleaning", symbolName = "dry_cleaning", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}checkroom", symbolName = "checkroom", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}local_laundry_service", symbolName = "local_laundry_service", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}monitor_weight", symbolName = "monitor_weight", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}local_florist", symbolName = "local_florist", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}energy_savings_leaf", symbolName = "energy_savings_leaf", drawableRes = null),
        ),
    ),
    IconCategory(
        nameRes = R.string.icon_section_content,
        icons = listOf(
            IconChoice(key = "${ICON_SYMBOL_PREFIX}archive", symbolName = "archive", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}details", symbolName = "details", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}add", symbolName = "add", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}add_circle", symbolName = "add_circle", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}add_circle_outline", symbolName = "add_circle_outline", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}remove", symbolName = "remove", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}remove_circle", symbolName = "remove_circle", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}remove_circle_outline", symbolName = "remove_circle_outline", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}restore_from_trash", symbolName = "restore_from_trash", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}delete_sweep", symbolName = "delete_sweep", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}flag", symbolName = "flag", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}gesture", symbolName = "gesture", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}copy_all", symbolName = "copy_all", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}shortcut", symbolName = "shortcut", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}content_paste", symbolName = "content_paste", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}select_all", symbolName = "select_all", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}edit", symbolName = "edit", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}inbox", symbolName = "inbox", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}unarchive", symbolName = "unarchive", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}drafts", symbolName = "drafts", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}backspace", symbolName = "backspace", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}save", symbolName = "save", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}camera", symbolName = "camera", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}picture_as_pdf", symbolName = "picture_as_pdf", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}link", symbolName = "link", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}reply", symbolName = "reply", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}reply_all", symbolName = "reply_all", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}undo", symbolName = "undo", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}redo", symbolName = "redo", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}low_priority", symbolName = "low_priority", drawableRes = null),
        ),
    ),
    IconCategory(
        nameRes = R.string.icon_section_editor,
        icons = listOf(
            IconChoice(key = "${ICON_SYMBOL_PREFIX}format_align_center", symbolName = "format_align_center", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}format_align_justify", symbolName = "format_align_justify", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}format_align_left", symbolName = "format_align_left", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}format_align_right", symbolName = "format_align_right", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}format_indent_increase", symbolName = "format_indent_increase", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}format_indent_decrease", symbolName = "format_indent_decrease", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}wrap_text", symbolName = "wrap_text", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}filter", symbolName = "filter", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}multiline_chart", symbolName = "multiline_chart", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}bar_chart", symbolName = "bar_chart", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}pie_chart", symbolName = "pie_chart", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}bubble_chart", symbolName = "bubble_chart", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}sort", symbolName = "sort", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}brush", symbolName = "brush", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}auto_fix_high", symbolName = "auto_fix_high", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}colorize", symbolName = "colorize", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}format_color_reset", symbolName = "format_color_reset", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}format_shapes", symbolName = "format_shapes", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}text_increase", symbolName = "text_increase", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}format_bold", symbolName = "format_bold", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}format_italic", symbolName = "format_italic", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}format_underlined", symbolName = "format_underlined", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}title", symbolName = "title", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}format_strikethrough", symbolName = "format_strikethrough", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}format_clear", symbolName = "format_clear", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}text_fields", symbolName = "text_fields", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}format_size", symbolName = "format_size", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}format_textdirection_l_to_r", symbolName = "format_textdirection_l_to_r", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}format_quote", symbolName = "format_quote", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}functions", symbolName = "functions", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}highlight", symbolName = "highlight", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}co_present", symbolName = "co_present", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}all_inclusive", symbolName = "all_inclusive", drawableRes = null),
        ),
    ),
    IconCategory(
        nameRes = R.string.icon_section_file,
        icons = listOf(
            IconChoice(key = "${ICON_SYMBOL_PREFIX}attachment", symbolName = "attachment", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}cloud", symbolName = "cloud", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}cloud_circle", symbolName = "cloud_circle", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}cloud_done", symbolName = "cloud_done", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}cloud_download", symbolName = "cloud_download", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}cloud_upload", symbolName = "cloud_upload", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}cloud_off", symbolName = "cloud_off", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}cloud_queue", symbolName = "cloud_queue", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}create_new_folder", symbolName = "create_new_folder", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}download", symbolName = "download", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}upload", symbolName = "upload", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}folder_open", symbolName = "folder_open", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}folder", symbolName = "folder", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}folder_shared", symbolName = "folder_shared", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}document_scanner", symbolName = "document_scanner", drawableRes = null),
        ),
    ),
    IconCategory(
        nameRes = R.string.icon_section_device,
        icons = listOf(
            IconChoice(key = "${ICON_SYMBOL_PREFIX}battery_full", symbolName = "battery_full", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}battery_alert", symbolName = "battery_alert", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}battery_charging_full", symbolName = "battery_charging_full", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}bluetooth", symbolName = "bluetooth", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}bluetooth_connected", symbolName = "bluetooth_connected", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}bluetooth_searching", symbolName = "bluetooth_searching", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}bluetooth_disabled", symbolName = "bluetooth_disabled", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}gps_fixed", symbolName = "gps_fixed", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}gps_not_fixed", symbolName = "gps_not_fixed", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}gps_off", symbolName = "gps_off", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}location_on", symbolName = "location_on", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}location_off", symbolName = "location_off", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}brightness_auto", symbolName = "brightness_auto", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}brightness_high", symbolName = "brightness_high", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}brightness_low", symbolName = "brightness_low", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}brightness_medium", symbolName = "brightness_medium", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}network_cell", symbolName = "network_cell", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}network_wifi", symbolName = "network_wifi", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}wifi", symbolName = "wifi", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}data_usage", symbolName = "data_usage", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}graphic_eq", symbolName = "graphic_eq", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}dialer_sip", symbolName = "dialer_sip", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}developer_mode", symbolName = "developer_mode", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}nfc", symbolName = "nfc", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}storage", symbolName = "storage", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}usb", symbolName = "usb", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}wallpaper", symbolName = "wallpaper", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}widgets", symbolName = "widgets", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}wifi_tethering", symbolName = "wifi_tethering", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}doorbell", symbolName = "doorbell", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}search", symbolName = "search", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}sync", symbolName = "sync", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}crop", symbolName = "crop", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}contrast", symbolName = "contrast", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}settings", symbolName = "settings", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}clear_all", symbolName = "clear_all", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}stop_circle", symbolName = "stop_circle", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}help", symbolName = "help", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}info", symbolName = "info", drawableRes = null),
        ),
    ),
    IconCategory(
        nameRes = R.string.icon_section_hardware,
        icons = listOf(
            IconChoice(key = "${ICON_SYMBOL_PREFIX}phone", symbolName = "phone", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}tablet", symbolName = "tablet", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}laptop", symbolName = "laptop", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}monitor", symbolName = "monitor", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}desktop_mac", symbolName = "desktop_mac", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}tv", symbolName = "tv", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}class", symbolName = "class", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}devices", symbolName = "devices", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}devices_other", symbolName = "devices_other", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}dock", symbolName = "dock", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}important_devices", symbolName = "important_devices", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}headphones", symbolName = "headphones", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}games", symbolName = "games", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}sports_esports", symbolName = "sports_esports", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}print", symbolName = "print", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}cast", symbolName = "cast", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}cast_connected", symbolName = "cast_connected", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}keyboard", symbolName = "keyboard", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}mouse", symbolName = "mouse", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}device_hub", symbolName = "device_hub", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}developer_board", symbolName = "developer_board", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}memory", symbolName = "memory", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}router", symbolName = "router", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}scanner", symbolName = "scanner", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}settings_input_composite", symbolName = "settings_input_composite", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}settings_input_hdmi", symbolName = "settings_input_hdmi", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}settings_input_svideo", symbolName = "settings_input_svideo", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}settings_remote", symbolName = "settings_remote", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}electrical_services", symbolName = "electrical_services", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}sd_storage", symbolName = "sd_storage", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}sim_card", symbolName = "sim_card", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}speaker", symbolName = "speaker", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}speaker_group", symbolName = "speaker_group", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}watch", symbolName = "watch", drawableRes = null),
        ),
    ),
    IconCategory(
        nameRes = R.string.icon_section_maps_travel,
        icons = listOf(
            IconChoice(key = "${ICON_SYMBOL_PREFIX}map", symbolName = "map", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}directions", symbolName = "directions", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}navigate_next", symbolName = "navigate_next", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}airplane_ticket", symbolName = "airplane_ticket", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}sd_card", symbolName = "sd_card", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}local_car_wash", symbolName = "local_car_wash", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}local_taxi", symbolName = "local_taxi", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}business", symbolName = "business", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}subway", symbolName = "subway", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}train", symbolName = "train", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}tram", symbolName = "tram", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}houseboat", symbolName = "houseboat", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}local_shipping", symbolName = "local_shipping", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}airport_shuttle", symbolName = "airport_shuttle", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}rv_hookup", symbolName = "rv_hookup", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}speed", symbolName = "speed", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}dashboard", symbolName = "dashboard", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}route", symbolName = "route", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}local_gas_station", symbolName = "local_gas_station", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}ev_station", symbolName = "ev_station", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}warning", symbolName = "warning", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}traffic", symbolName = "traffic", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}add_road", symbolName = "add_road", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}compass_calibration", symbolName = "compass_calibration", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}flash_on", symbolName = "flash_on", drawableRes = null),
        ),
    ),
    IconCategory(
        nameRes = R.string.icon_section_weather,
        icons = listOf(
            IconChoice(key = "${ICON_SYMBOL_PREFIX}umbrella", symbolName = "umbrella", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}ac_unit", symbolName = "ac_unit", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}wb_sunny", symbolName = "wb_sunny", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}air", symbolName = "air", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}wb_cloudy", symbolName = "wb_cloudy", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}grain", symbolName = "grain", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}severe_cold", symbolName = "severe_cold", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}hail", symbolName = "hail", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}thunderstorm", symbolName = "thunderstorm", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}thermostat", symbolName = "thermostat", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}thermostat_auto", symbolName = "thermostat_auto", drawableRes = null),
        ),
    ),
    IconCategory(
        nameRes = R.string.icon_section_media,
        icons = listOf(
            IconChoice(key = "${ICON_SYMBOL_PREFIX}radio", symbolName = "radio", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}hearing", symbolName = "hearing", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}volume_up", symbolName = "volume_up", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}volume_down", symbolName = "volume_down", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}volume_mute", symbolName = "volume_mute", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}skip_previous", symbolName = "skip_previous", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}skip_next", symbolName = "skip_next", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}fast_rewind", symbolName = "fast_rewind", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}fast_forward", symbolName = "fast_forward", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}play_arrow", symbolName = "play_arrow", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}pause", symbolName = "pause", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}stop", symbolName = "stop", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}shuffle", symbolName = "shuffle", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}repeat", symbolName = "repeat", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}queue_music", symbolName = "queue_music", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}playlist_play", symbolName = "playlist_play", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}playlist_add", symbolName = "playlist_add", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}playlist_add_check", symbolName = "playlist_add_check", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}movie", symbolName = "movie", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}videocam", symbolName = "videocam", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}video_call", symbolName = "video_call", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}videocam_off", symbolName = "videocam_off", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}equalizer", symbolName = "equalizer", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}record_voice_over", symbolName = "record_voice_over", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}new_releases", symbolName = "new_releases", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}closed_caption", symbolName = "closed_caption", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}fiber_dvr", symbolName = "fiber_dvr", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}library_add", symbolName = "library_add", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}library_books", symbolName = "library_books", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}library_music", symbolName = "library_music", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}video_library", symbolName = "video_library", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}recent_actors", symbolName = "recent_actors", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}subscriptions", symbolName = "subscriptions", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}subtitles", symbolName = "subtitles", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}surround_sound", symbolName = "surround_sound", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}av_timer", symbolName = "av_timer", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}slow_motion_video", symbolName = "slow_motion_video", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}add_to_queue", symbolName = "add_to_queue", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}queue_play_next", symbolName = "queue_play_next", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}remove_from_queue", symbolName = "remove_from_queue", drawableRes = null),
        ),
    ),
    IconCategory(
        nameRes = R.string.icon_section_navigation,
        icons = listOf(
            IconChoice(key = "${ICON_SYMBOL_PREFIX}view_module", symbolName = "view_module", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}sticky_note_2", symbolName = "sticky_note_2", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}cancel", symbolName = "cancel", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}arrow_drop_down_circle", symbolName = "arrow_drop_down_circle", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}menu", symbolName = "menu", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}arrow_left", symbolName = "arrow_left", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}arrow_right", symbolName = "arrow_right", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}keyboard_arrow_up", symbolName = "keyboard_arrow_up", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}keyboard_arrow_down", symbolName = "keyboard_arrow_down", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}subdirectory_arrow_left", symbolName = "subdirectory_arrow_left", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}subdirectory_arrow_right", symbolName = "subdirectory_arrow_right", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}first_page", symbolName = "first_page", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}last_page", symbolName = "last_page", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}chevron_left", symbolName = "chevron_left", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}chevron_right", symbolName = "chevron_right", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}expand_more", symbolName = "expand_more", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}expand_less", symbolName = "expand_less", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}fullscreen", symbolName = "fullscreen", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}fullscreen_exit", symbolName = "fullscreen_exit", drawableRes = null),
        ),
    ),
    IconCategory(
        nameRes = R.string.icon_section_people,
        icons = listOf(
            IconChoice(key = "${ICON_SYMBOL_PREFIX}person_add", symbolName = "person_add", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}groups", symbolName = "groups", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}group_add", symbolName = "group_add", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}accessibility", symbolName = "accessibility", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}masks", symbolName = "masks", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}child_care", symbolName = "child_care", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}mood", symbolName = "mood", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}mood_bad", symbolName = "mood_bad", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}sentiment_very_satisfied", symbolName = "sentiment_very_satisfied", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}sentiment_satisfied", symbolName = "sentiment_satisfied", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}sentiment_neutral", symbolName = "sentiment_neutral", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}sentiment_dissatisfied", symbolName = "sentiment_dissatisfied", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}sentiment_very_dissatisfied", symbolName = "sentiment_very_dissatisfied", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}pets", symbolName = "pets", drawableRes = null),
        ),
    ),
    IconCategory(
        nameRes = R.string.icon_section_sports,
        icons = listOf(
            IconChoice(key = "${ICON_SYMBOL_PREFIX}nordic_walking", symbolName = "nordic_walking", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}hiking", symbolName = "hiking", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}roller_skating", symbolName = "roller_skating", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}running_with_errors", symbolName = "running_with_errors", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}skateboarding", symbolName = "skateboarding", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}ice_skating", symbolName = "ice_skating", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}downhill_skiing", symbolName = "downhill_skiing", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}snowboarding", symbolName = "snowboarding", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}rowing", symbolName = "rowing", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}sports_martial_arts", symbolName = "sports_martial_arts", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}pool", symbolName = "pool", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}wheelchair_pickup", symbolName = "wheelchair_pickup", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}sports_tennis", symbolName = "sports_tennis", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}sports_score", symbolName = "sports_score", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}sports_soccer", symbolName = "sports_soccer", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}sports_football", symbolName = "sports_football", drawableRes = null),
        ),
    ),
    IconCategory(
        nameRes = R.string.icon_section_places,
        icons = listOf(
            IconChoice(key = "${ICON_SYMBOL_PREFIX}travel_explore", symbolName = "travel_explore", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}home", symbolName = "home", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}domain", symbolName = "domain", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}opacity", symbolName = "opacity", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}school", symbolName = "school", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}church", symbolName = "church", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}factory", symbolName = "factory", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}castle", symbolName = "castle", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}build", symbolName = "build", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}local_hospital", symbolName = "local_hospital", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}local_pharmacy", symbolName = "local_pharmacy", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}medical_services", symbolName = "medical_services", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}healing", symbolName = "healing", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}monitor_heart", symbolName = "monitor_heart", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}medication", symbolName = "medication", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}markunread_mailbox", symbolName = "markunread_mailbox", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}gavel", symbolName = "gavel", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}hot_tub", symbolName = "hot_tub", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}kitchen", symbolName = "kitchen", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}fitness_center", symbolName = "fitness_center", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}golf_course", symbolName = "golf_course", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}room_service", symbolName = "room_service", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}spa", symbolName = "spa", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}beach_access", symbolName = "beach_access", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}business_center", symbolName = "business_center", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}child_friendly", symbolName = "child_friendly", drawableRes = null),
        ),
    ),
    IconCategory(
        nameRes = R.string.icon_section_food_drink,
        icons = listOf(
            IconChoice(key = "${ICON_SYMBOL_PREFIX}restaurant", symbolName = "restaurant", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}restaurant_menu", symbolName = "restaurant_menu", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}cake", symbolName = "cake", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}local_pizza", symbolName = "local_pizza", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}coffee", symbolName = "coffee", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}local_bar", symbolName = "local_bar", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}local_cafe", symbolName = "local_cafe", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}smoke_free", symbolName = "smoke_free", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}smoking_rooms", symbolName = "smoking_rooms", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}set_meal", symbolName = "set_meal", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}category", symbolName = "category", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}egg_alt", symbolName = "egg_alt", drawableRes = null),
        ),
    ),
    IconCategory(
        nameRes = R.string.icon_section_leisure,
        icons = listOf(
            IconChoice(key = "${ICON_SYMBOL_PREFIX}sell", symbolName = "sell", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}code", symbolName = "code", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}celebration", symbolName = "celebration", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}card_giftcard", symbolName = "card_giftcard", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}emoji_events", symbolName = "emoji_events", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}ballot", symbolName = "ballot", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}casino", symbolName = "casino", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}extension", symbolName = "extension", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}piano", symbolName = "piano", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}music_note", symbolName = "music_note", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}poll", symbolName = "poll", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}pages", symbolName = "pages", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}grade", symbolName = "grade", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}share", symbolName = "share", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}whatshot", symbolName = "whatshot", drawableRes = null),
        ),
    ),
    IconCategory(
        nameRes = R.string.icon_section_toggle,
        icons = listOf(
            IconChoice(key = "${ICON_SYMBOL_PREFIX}check_box", symbolName = "check_box", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}check_box_outline_blank", symbolName = "check_box_outline_blank", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}indeterminate_check_box", symbolName = "indeterminate_check_box", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}radio_button_checked", symbolName = "radio_button_checked", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}radio_button_unchecked", symbolName = "radio_button_unchecked", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}star", symbolName = "star", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}star_border", symbolName = "star_border", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}star_half", symbolName = "star_half", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}filter_none", symbolName = "filter_none", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}filter_1", symbolName = "filter_1", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}filter_2", symbolName = "filter_2", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}looks_3", symbolName = "looks_3", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}looks_4", symbolName = "looks_4", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}looks_5", symbolName = "looks_5", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}looks_6", symbolName = "looks_6", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}filter_7", symbolName = "filter_7", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}filter_8", symbolName = "filter_8", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}filter_9", symbolName = "filter_9", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}filter_9_plus", symbolName = "filter_9_plus", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}filter_3", symbolName = "filter_3", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}filter_4", symbolName = "filter_4", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}filter_5", symbolName = "filter_5", drawableRes = null),
            IconChoice(key = "${ICON_SYMBOL_PREFIX}filter_6", symbolName = "filter_6", drawableRes = null),
        ),
    ),
    IconCategory(
        nameRes = R.string.icon_section_brands,
        icons = listOf(
            IconChoice(key = "${ICON_DRAWABLE_PREFIX}ic_action_amazon", symbolName = null, drawableRes = R.drawable.ic_action_amazon),
            IconChoice(key = "${ICON_DRAWABLE_PREFIX}ic_stat_amazon_alexa", symbolName = null, drawableRes = R.drawable.ic_stat_amazon_alexa),
            IconChoice(key = "${ICON_DRAWABLE_PREFIX}ic_action_android", symbolName = null, drawableRes = R.drawable.ic_action_android),
            IconChoice(key = "${ICON_DRAWABLE_PREFIX}ic_stat_adb", symbolName = null, drawableRes = R.drawable.ic_stat_adb),
            IconChoice(key = "${ICON_DRAWABLE_PREFIX}ic_stat_android_auto", symbolName = null, drawableRes = R.drawable.ic_stat_android_auto),
            IconChoice(key = "${ICON_DRAWABLE_PREFIX}ic_stat_android_studio", symbolName = null, drawableRes = R.drawable.ic_stat_android_studio),
            IconChoice(key = "${ICON_DRAWABLE_PREFIX}ic_stat_apple", symbolName = null, drawableRes = R.drawable.ic_stat_apple),
            IconChoice(key = "${ICON_DRAWABLE_PREFIX}ic_stat_beats", symbolName = null, drawableRes = R.drawable.ic_stat_beats),
            IconChoice(key = "${ICON_DRAWABLE_PREFIX}ic_stat_behance", symbolName = null, drawableRes = R.drawable.ic_stat_behance),
            IconChoice(key = "${ICON_DRAWABLE_PREFIX}ic_stat_blackberry", symbolName = null, drawableRes = R.drawable.ic_stat_blackberry),
            IconChoice(key = "${ICON_DRAWABLE_PREFIX}ic_stat_codepen", symbolName = null, drawableRes = R.drawable.ic_stat_codepen),
            IconChoice(key = "${ICON_DRAWABLE_PREFIX}ic_stat_disqus", symbolName = null, drawableRes = R.drawable.ic_stat_disqus),
            IconChoice(key = "${ICON_DRAWABLE_PREFIX}ic_stat_dribbble", symbolName = null, drawableRes = R.drawable.ic_stat_dribbble),
            IconChoice(key = "${ICON_DRAWABLE_PREFIX}ic_stat_drive", symbolName = null, drawableRes = R.drawable.ic_stat_drive),
            IconChoice(key = "${ICON_DRAWABLE_PREFIX}ic_action_dropbox", symbolName = null, drawableRes = R.drawable.ic_action_dropbox),
            IconChoice(key = "${ICON_DRAWABLE_PREFIX}ic_stat_edge", symbolName = null, drawableRes = R.drawable.ic_stat_edge),
            IconChoice(key = "${ICON_DRAWABLE_PREFIX}ic_action_facebook", symbolName = null, drawableRes = R.drawable.ic_action_facebook),
            IconChoice(key = "${ICON_DRAWABLE_PREFIX}ic_stat_facebook_messenger", symbolName = null, drawableRes = R.drawable.ic_stat_facebook_messenger),
            IconChoice(key = "${ICON_DRAWABLE_PREFIX}ic_stat_firebase", symbolName = null, drawableRes = R.drawable.ic_stat_firebase),
            IconChoice(key = "${ICON_DRAWABLE_PREFIX}ic_stat_firefox", symbolName = null, drawableRes = R.drawable.ic_stat_firefox),
            IconChoice(key = "${ICON_DRAWABLE_PREFIX}ic_action_foursquare", symbolName = null, drawableRes = R.drawable.ic_action_foursquare),
            IconChoice(key = "${ICON_DRAWABLE_PREFIX}ic_action_github", symbolName = null, drawableRes = R.drawable.ic_action_github),
            IconChoice(key = "${ICON_DRAWABLE_PREFIX}ic_stat_google", symbolName = null, drawableRes = R.drawable.ic_stat_google),
            IconChoice(key = "${ICON_DRAWABLE_PREFIX}ic_action_gplus", symbolName = null, drawableRes = R.drawable.ic_action_gplus),
            IconChoice(key = "${ICON_DRAWABLE_PREFIX}ic_action_gmail", symbolName = null, drawableRes = R.drawable.ic_action_gmail),
            IconChoice(key = "${ICON_DRAWABLE_PREFIX}ic_stat_google_hangouts", symbolName = null, drawableRes = R.drawable.ic_stat_google_hangouts),
            IconChoice(key = "${ICON_DRAWABLE_PREFIX}ic_stat_google_assistant", symbolName = null, drawableRes = R.drawable.ic_stat_google_assistant),
            IconChoice(key = "${ICON_DRAWABLE_PREFIX}ic_stat_google_allo", symbolName = null, drawableRes = R.drawable.ic_stat_google_allo),
            IconChoice(key = "${ICON_DRAWABLE_PREFIX}ic_stat_google_earth", symbolName = null, drawableRes = R.drawable.ic_stat_google_earth),
            IconChoice(key = "${ICON_DRAWABLE_PREFIX}ic_stat_google_fit", symbolName = null, drawableRes = R.drawable.ic_stat_google_fit),
            IconChoice(key = "${ICON_DRAWABLE_PREFIX}ic_action_google_play", symbolName = null, drawableRes = R.drawable.ic_action_google_play),
            IconChoice(key = "${ICON_DRAWABLE_PREFIX}ic_stat_google_home", symbolName = null, drawableRes = R.drawable.ic_stat_google_home),
            IconChoice(key = "${ICON_DRAWABLE_PREFIX}ic_stat_google_cardboard", symbolName = null, drawableRes = R.drawable.ic_stat_google_cardboard),
            IconChoice(key = "${ICON_DRAWABLE_PREFIX}ic_stat_hulu", symbolName = null, drawableRes = R.drawable.ic_stat_hulu),
            IconChoice(key = "${ICON_DRAWABLE_PREFIX}ic_stat_instagram", symbolName = null, drawableRes = R.drawable.ic_stat_instagram),
            IconChoice(key = "${ICON_DRAWABLE_PREFIX}ic_stat_itunes", symbolName = null, drawableRes = R.drawable.ic_stat_itunes),
            IconChoice(key = "${ICON_DRAWABLE_PREFIX}ic_stat_kickstarter", symbolName = null, drawableRes = R.drawable.ic_stat_kickstarter),
            IconChoice(key = "${ICON_DRAWABLE_PREFIX}ic_stat_kodi", symbolName = null, drawableRes = R.drawable.ic_stat_kodi),
            IconChoice(key = "${ICON_DRAWABLE_PREFIX}ic_stat_lastpass", symbolName = null, drawableRes = R.drawable.ic_stat_lastpass),
            IconChoice(key = "${ICON_DRAWABLE_PREFIX}ic_action_linkedin", symbolName = null, drawableRes = R.drawable.ic_action_linkedin),
            IconChoice(key = "${ICON_DRAWABLE_PREFIX}ic_stat_maxcdn", symbolName = null, drawableRes = R.drawable.ic_stat_maxcdn),
            IconChoice(key = "${ICON_DRAWABLE_PREFIX}ic_stat_medium", symbolName = null, drawableRes = R.drawable.ic_stat_medium),
            IconChoice(key = "${ICON_DRAWABLE_PREFIX}ic_stat_netflix", symbolName = null, drawableRes = R.drawable.ic_stat_netflix),
            IconChoice(key = "${ICON_DRAWABLE_PREFIX}ic_stat_office", symbolName = null, drawableRes = R.drawable.ic_stat_office),
            IconChoice(key = "${ICON_DRAWABLE_PREFIX}ic_stat_pandora", symbolName = null, drawableRes = R.drawable.ic_stat_pandora),
            IconChoice(key = "${ICON_DRAWABLE_PREFIX}ic_stat_patreon", symbolName = null, drawableRes = R.drawable.ic_stat_patreon),
            IconChoice(key = "${ICON_DRAWABLE_PREFIX}ic_action_paypal", symbolName = null, drawableRes = R.drawable.ic_action_paypal),
            IconChoice(key = "${ICON_DRAWABLE_PREFIX}ic_stat_periscope", symbolName = null, drawableRes = R.drawable.ic_stat_periscope),
            IconChoice(key = "${ICON_DRAWABLE_PREFIX}ic_action_pinterest", symbolName = null, drawableRes = R.drawable.ic_action_pinterest),
            IconChoice(key = "${ICON_DRAWABLE_PREFIX}ic_stat_plex", symbolName = null, drawableRes = R.drawable.ic_stat_plex),
            IconChoice(key = "${ICON_DRAWABLE_PREFIX}ic_stat_pocket", symbolName = null, drawableRes = R.drawable.ic_stat_pocket),
            IconChoice(key = "${ICON_DRAWABLE_PREFIX}ic_stat_reddit", symbolName = null, drawableRes = R.drawable.ic_stat_reddit),
            IconChoice(key = "${ICON_DRAWABLE_PREFIX}ic_stat_skype", symbolName = null, drawableRes = R.drawable.ic_stat_skype),
            IconChoice(key = "${ICON_DRAWABLE_PREFIX}ic_stat_slack", symbolName = null, drawableRes = R.drawable.ic_stat_slack),
            IconChoice(key = "${ICON_DRAWABLE_PREFIX}ic_stat_snapchat", symbolName = null, drawableRes = R.drawable.ic_stat_snapchat),
            IconChoice(key = "${ICON_DRAWABLE_PREFIX}ic_stat_spotify", symbolName = null, drawableRes = R.drawable.ic_stat_spotify),
            IconChoice(key = "${ICON_DRAWABLE_PREFIX}ic_stat_square_inc", symbolName = null, drawableRes = R.drawable.ic_stat_square_inc),
            IconChoice(key = "${ICON_DRAWABLE_PREFIX}ic_stat_square_inc_cash", symbolName = null, drawableRes = R.drawable.ic_stat_square_inc_cash),
            IconChoice(key = "${ICON_DRAWABLE_PREFIX}ic_stat_steam", symbolName = null, drawableRes = R.drawable.ic_stat_steam),
            IconChoice(key = "${ICON_DRAWABLE_PREFIX}ic_action_stumbleupon", symbolName = null, drawableRes = R.drawable.ic_action_stumbleupon),
            IconChoice(key = "${ICON_DRAWABLE_PREFIX}ic_stat_telegram", symbolName = null, drawableRes = R.drawable.ic_stat_telegram),
            IconChoice(key = "${ICON_DRAWABLE_PREFIX}ic_action_tumblr", symbolName = null, drawableRes = R.drawable.ic_action_tumblr),
            IconChoice(key = "${ICON_DRAWABLE_PREFIX}ic_stat_twitch", symbolName = null, drawableRes = R.drawable.ic_stat_twitch),
            IconChoice(key = "${ICON_DRAWABLE_PREFIX}ic_action_twitter", symbolName = null, drawableRes = R.drawable.ic_action_twitter),
            IconChoice(key = "${ICON_DRAWABLE_PREFIX}ic_stat_venmo", symbolName = null, drawableRes = R.drawable.ic_stat_venmo),
            IconChoice(key = "${ICON_DRAWABLE_PREFIX}ic_action_vimeo", symbolName = null, drawableRes = R.drawable.ic_action_vimeo),
            IconChoice(key = "${ICON_DRAWABLE_PREFIX}ic_stat_vine", symbolName = null, drawableRes = R.drawable.ic_stat_vine),
            IconChoice(key = "${ICON_DRAWABLE_PREFIX}ic_stat_whatsapp", symbolName = null, drawableRes = R.drawable.ic_stat_whatsapp),
            IconChoice(key = "${ICON_DRAWABLE_PREFIX}ic_stat_windows", symbolName = null, drawableRes = R.drawable.ic_stat_windows),
            IconChoice(key = "${ICON_DRAWABLE_PREFIX}ic_action_youtube", symbolName = null, drawableRes = R.drawable.ic_action_youtube),
            IconChoice(key = "${ICON_DRAWABLE_PREFIX}ic_stat_youtube_gaming", symbolName = null, drawableRes = R.drawable.ic_stat_youtube_gaming),
            IconChoice(key = "${ICON_DRAWABLE_PREFIX}ic_stat_youtube_tv", symbolName = null, drawableRes = R.drawable.ic_stat_youtube_tv),
        ),
    ),
)

